[desktop]
  http_host = 0.0.0.0
  http_port = 8888
  time_zone = Asia/Shanghai
  # 首个注册用户即超级管理员
  sentry_enabled = false

[beeswax]
  # HiveServer2（hive-server 容器）
  hive_server_host = hive
  hive_server_port = 10000

[hadoop]
  [[hdfs_clusters]]
    [[[default]]]
      fs_defaultfs = hdfs://hadoop:8020
      webhdfs_url = http://hadoop:9870/webhdfs/v1
      hadoop_conf_dir = /opt/hadoop/etc/hadoop
      is_enabled = true
  [[yarn_clusters]]
    [[[default]]]
      resourcemanager_api_url = http://hadoop:8088
      proxy_api_url = http://hadoop:8088
      history_server_api_url = http://hadoop:19888
      hadoop_conf_dir = /opt/hadoop/etc/hadoop
      is_enabled = true
